// freddy/server/frontend/src/pages/Dashboard.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { dashboardApi } from "../lib/api";
  import { money, numberValue, shortMoney, dateTime } from "../lib/format";
  import { navigate, routePath } from "../lib/router";
  import type { DashboardStats } from "../lib/types";
  import BarChart from "../lib/components/BarChart.svelte";
  import DonutChart from "../lib/components/DonutChart.svelte";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import LineChart from "../lib/components/LineChart.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import StatCard from "../lib/components/StatCard.svelte";
  import StatusBadge from "../lib/components/StatusBadge.svelte";

  let stats: DashboardStats | null = null;
  let trend: Array<{ label: string; value: number }> = [];
  let days = 30;
  let loading = true;
  let error = "";

  async function load(): Promise<void> {
    loading = true;
    error = "";
    try {
      const [dashboard, chart] = await Promise.all([dashboardApi.stats(), dashboardApi.chart(days)]);
      stats = dashboard;
      trend = chart.data.map((point) => ({ label: point.date, value: numberValue(point.amount) }));
    } catch (err) {
      error = err instanceof Error ? err.message : "Unable to load dashboard.";
    } finally { loading = false; }
  }

  onMount(load);

  $: companyBars = stats?.by_company.map((row) => ({ label: String(row["station__company__name"] || "—"), value: numberValue(row.total) })) || [];
  $: fuelBars = stats?.by_fuel.map((row) => ({ label: String(row["fuel_type__name"] || "—"), value: numberValue(row.total) })) || [];
</script>

<div class="page-heading"><div><h2>Dashboard</h2><p>Live overview of collection, verification, and disbursement activity.</p></div><div class="heading-actions"><button class:active={days === 7} class="btn btn-quiet" on:click={() => { days = 7; load(); }}>7 days</button><button class:active={days === 30} class="btn btn-quiet" on:click={() => { days = 30; load(); }}>30 days</button><button class:active={days === 90} class="btn btn-quiet" on:click={() => { days = 90; load(); }}>90 days</button><button class="btn" on:click={load}>↻ Refresh</button></div></div>

{#if loading}<Loading />
{:else if error}<ErrorState message={error} retry={load} />
{:else if stats}
  <div class="kpi-grid">
    <StatCard label="Today’s levy" value={money(stats.today_levy)} hint={`${stats.today_count} transactions`} tone="accent" />
    <StatCard label="This month" value={money(stats.month_levy)} hint={`${stats.month_count} transactions`} tone="success" />
    <StatCard label="Total levy" value={money(stats.total_levy)} hint={`${stats.total_count} records`} />
    <StatCard label="Pending" value={stats.pending_count} hint={`${stats.verified_count} verified · ${stats.remitted_count} remitted`} tone="warning" />
  </div>

  <div class="grid grid-wide">
    <section class="card card-pad"><div class="split"><div><h3 class="section-title">Levy trend</h3><p class="section-subtitle">Collected levy in USD</p></div><span class="status status-verified">{days} days</span></div><LineChart points={trend} /></section>
    <section class="card card-pad"><div><h3 class="section-title">Transaction status</h3><p class="section-subtitle">Current distribution</p></div><DonutChart values={[stats.pending_count, stats.verified_count, stats.remitted_count]} labels={["Pending", "Verified", "Remitted"]} /></section>
  </div>

  <div class="grid grid-2" style="margin-top:16px">
    <section class="card card-pad"><h3 class="section-title">Levy by company</h3><p class="section-subtitle">Scoped to your account</p><BarChart items={companyBars} /></section>
    <section class="card card-pad"><h3 class="section-title">Levy by fuel type</h3><p class="section-subtitle">Contribution by fuel</p><BarChart items={fuelBars} color="#15803d" /></section>
  </div>

  <section class="card card-pad" style="margin-top:16px"><div class="split"><div><h3 class="section-title">Top stations this month</h3><p class="section-subtitle">Progress against monthly targets</p></div><span class="muted" style="font-size:11px">Paid out: {money(stats.total_disbursed)}</span></div>
    <div class="grid grid-3" style="margin-top:16px">
      {#each stats.top_stations as station}
        <button class="station-card" on:click={() => navigate(routePath("station-detail", station.id))}><div class="split"><strong>{station.name}</strong><span class="money">{money(station.month_levy)}</span></div><p>{station.company_name}</p>{#if station.target_pct !== null}<div class="progress"><span style={`width:${station.target_pct}%`}></span></div><small>{station.target_pct}% of {money(station.target_usd)}</small>{:else}<small>No target set</small>{/if}</button>
      {:else}<div class="empty-state">No active stations yet.</div>{/each}
    </div>
  </section>

  <section class="card" style="margin-top:16px"><div class="card-header"><div><h3>Recent transactions</h3><p>Latest activity in your scope</p></div><a class="btn btn-quiet" href={routePath("transactions")} on:click={(event) => { event.preventDefault(); navigate(routePath("transactions")); }}>View all →</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Receipt</th><th>Station</th><th>Church</th><th>Levy</th><th>Status</th><th>Date</th></tr></thead><tbody>{#each stats.recent as tx}<tr><td><a class="text-link receipt-code" href={routePath("transaction-detail", tx.id)} on:click={(event) => { event.preventDefault(); navigate(routePath("transaction-detail", tx.id)); }}>{tx.receipt_code}</a></td><td>{tx.station_name}</td><td>{tx.church_name}</td><td class="money">{money(tx.levy_amount_usd)}</td><td><StatusBadge status={tx.status} /></td><td class="muted nowrap">{dateTime(tx.created_at)}</td></tr>{:else}<tr><td colspan="6"><div class="empty-state">No transactions yet.</div></td></tr>{/each}</tbody></table></div></section>
{:else}<div class="empty-state">No dashboard data.</div>{/if}

<style>
  .heading-actions .active{background:var(--accent-soft);color:var(--accent);border-color:#b9c8d8}
  .station-card{border:1px solid var(--line);background:var(--surface);border-radius:9px;padding:14px;text-align:left;transition:.15s}
  .station-card:hover{border-color:#b9c8d8;box-shadow:0 3px 10px rgb(28 33 38 / .06)}
  .station-card strong{font-size:13px}.station-card .money{font-size:12px}.station-card p{font-size:11px;color:var(--muted);margin:5px 0 13px}.station-card small{display:block;color:var(--muted);font-size:10px;margin-top:6px}
</style>

// freddy/server/spa/src/pages/Dashboard.tsx
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import { Bar, Doughnut, Line } from "react-chartjs-2";
import { Link } from "react-router-dom";

import { request } from "@/api/client";
import type { ChartPoint, DashboardStats } from "@/api/types";
import { Card, EmptyState, ErrorState, KpiCard, Spinner, StatusBadge } from "@/components/ui";
import {
  accent,
  accentSoft,
  barOptions,
  lineOptions,
  doughnutOptions,
  doughnutSegment,
  palette,
  statusColors,
} from "@/charts/theme";
import { dateTime, number, percent, usd } from "@/lib/format";

const DAY_PRESETS = [7, 30, 90];

export default function Dashboard() {
  const { t } = useTranslation();
  const [days, setDays] = useState(30);

  const statsQuery = useQuery({
    queryKey: ["dashboard", "stats"],
    queryFn: () => request<DashboardStats>("/dashboard/stats/"),
    // Matches the 20s htmx poll the Django dashboard uses.
    refetchInterval: 20_000,
  });

  const chartQuery = useQuery({
    queryKey: ["dashboard", "chart", days],
    queryFn: () => request<{ data: ChartPoint[] }>("/dashboard/chart/", { params: { days } }),
  });

  if (statsQuery.isLoading) return <Spinner />;
  if (statsQuery.isError) {
    return <ErrorState onRetry={() => void statsQuery.refetch()} />;
  }

  const stats = statsQuery.data!;

  return (
    <div className="space-y-4">
      <header>
        <h1 className="text-lg font-semibold">{t("dashboard.title")}</h1>
        <p className="text-xs text-muted">{t("dashboard.subtitle")}</p>
      </header>

      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
        <KpiCard
          label={t("dashboard.todayLevy")}
          value={usd(stats.today_levy)}
          hint={`${number(stats.today_count)} ${t("dashboard.todayCount")}`}
          accent
        />
        <KpiCard
          label={t("dashboard.monthLevy")}
          value={usd(stats.month_levy)}
          hint={`${number(stats.month_count)} ${t("dashboard.monthCount")}`}
          accent
        />
        <KpiCard
          label={t("dashboard.totalLevy")}
          value={usd(stats.total_levy)}
          hint={`${number(stats.total_count)} ${t("dashboard.totalCount")}`}
          accent
        />
        <KpiCard
          label={t("dashboard.disbursed")}
          value={usd(stats.total_disbursed)}
          hint={`${number(stats.pending_disburse)} ${t("dashboard.pendingDisburse")}`}
        />
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Card
          className="lg:col-span-2"
          title={t("dashboard.trend")}
          actions={
            <div className="flex gap-1">
              {DAY_PRESETS.map((preset) => (
                <button
                  key={preset}
                  type="button"
                  className={`btn ${days === preset ? "btn-primary" : "btn-quiet"}`}
                  onClick={() => setDays(preset)}
                >
                  {t("dashboard.days", { count: preset })}
                </button>
              ))}
            </div>
          }
        >
          <div className="h-64">
            {chartQuery.isLoading ? (
              <Spinner />
            ) : (
              <Line
                options={lineOptions}
                data={{
                  labels: chartQuery.data?.data.map((point) => point.date) ?? [],
                  datasets: [
                    {
                      label: t("tx.levy"),
                      data: chartQuery.data?.data.map((point) => point.amount) ?? [],
                      borderColor: accent,
                      backgroundColor: accentSoft,
                      fill: true,
                      tension: 0.35,
                      pointRadius: 0,
                      pointHoverRadius: 4,
                    },
                  ],
                }}
              />
            )}
          </div>
        </Card>

        <Card title={t("dashboard.byStatus")}>
          <div className="h-64">
            <Doughnut
              options={doughnutOptions}
              data={{
                labels: [
                  t("status.PENDING"),
                  t("status.VERIFIED"),
                  t("status.REMITTED"),
                ],
                datasets: [
                  {
                    data: [stats.pending_count, stats.verified_count, stats.remitted_count],
                    backgroundColor: [
                      statusColors.PENDING,
                      statusColors.VERIFIED,
                      statusColors.REMITTED,
                    ],
                    ...doughnutSegment,
                  },
                ],
              }}
            />
          </div>
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2" title={t("dashboard.byCompany")}>
          <div className="h-56">
            <Bar
              options={barOptions}
              data={{
                labels: stats.by_company.map((row) => row.station__company__name),
                datasets: [
                  {
                    label: t("tx.levyUsd"),
                    data: stats.by_company.map((row) => row.total),
                    backgroundColor: palette[0],
                    borderRadius: 4,
                  },
                ],
              }}
            />
          </div>
        </Card>

        <Card title={t("dashboard.byFuel")}>
          <div className="h-56">
            <Doughnut
              options={doughnutOptions}
              data={{
                labels: stats.by_fuel.map((row) => row.fuel_type__name),
                datasets: [
                  {
                    data: stats.by_fuel.map((row) => row.total),
                    backgroundColor: palette,
                    ...doughnutSegment,
                  },
                ],
              }}
            />
          </div>
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        <Card title={t("dashboard.topStations")}>
          {stats.top_stations.length === 0 ? (
            <EmptyState message={t("dashboard.noStations")} />
          ) : (
            <div className="space-y-3">
              {stats.top_stations.map((station) => (
                <div key={station.id}>
                  <div className="flex items-baseline justify-between gap-2">
                    <Link
                      to={`/stations/${station.id}`}
                      className="truncate text-sm font-medium hover:underline"
                    >
                      {station.name}
                    </Link>
                    <span className="money flex-shrink-0 text-xs">
                      {usd(station.month_levy)}
                    </span>
                  </div>
                  {station.target_pct !== null ? (
                    <>
                      <div className="mt-1 h-1.5 overflow-hidden rounded-full bg-surface-2">
                        <div
                          className={`h-full rounded-full ${
                            station.target_pct >= 100 ? "bg-ok" : "bg-accent"
                          }`}
                          style={{ width: `${station.target_pct}%` }}
                        />
                      </div>
                      <p className="mt-0.5 text-[10px] text-muted">
                        {percent(station.target_pct)} {t("dashboard.ofTarget")}{" "}
                        {usd(station.target_usd, 0)}
                      </p>
                    </>
                  ) : (
                    <p className="mt-0.5 text-[10px] text-muted">
                      {station.company_name} · {t("dashboard.noTarget")}
                    </p>
                  )}
                </div>
              ))}
            </div>
          )}
        </Card>

        <Card className="lg:col-span-2" title={t("dashboard.recent")} bodyClassName="">
          {stats.recent.length === 0 ? (
            <EmptyState message={t("common.noResults")} />
          ) : (
            <div className="overflow-x-auto">
              <table className="tbl tbl-zebra">
                <thead>
                  <tr>
                    <th>{t("tx.receipt")}</th>
                    <th>{t("tx.station")}</th>
                    <th>{t("tx.levyUsd")}</th>
                    <th>{t("common.status")}</th>
                    <th>{t("common.date")}</th>
                  </tr>
                </thead>
                <tbody>
                  {stats.recent.map((tx) => (
                    <tr key={tx.id}>
                      <td>
                        <Link
                          to={`/transactions/${tx.id}`}
                          className="receipt-code hover:underline"
                        >
                          {tx.receipt_code}
                        </Link>
                      </td>
                      <td className="truncate">{tx.station_name}</td>
                      <td className="money num">{usd(tx.levy_amount_usd)}</td>
                      <td>
                        <StatusBadge status={tx.status} />
                      </td>
                      <td className="whitespace-nowrap text-xs text-muted">
                        {dateTime(tx.created_at)}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
}
