// freddy/server/frontend/src/pages/TransactionDetail.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import { can } from "../lib/auth";
  import { transactionsApi } from "../lib/api";
  import { dateTime, money } from "../lib/format";
  import { navigate, routePath } from "../lib/router";
  import type { AuditLog, Transaction } from "../lib/types";
  import ErrorState from "../lib/components/ErrorState.svelte";
  import Loading from "../lib/components/Loading.svelte";
  import StatusBadge from "../lib/components/StatusBadge.svelte";

  export let id: string;
  let tx: (Transaction & { audit_logs: AuditLog[] }) | null = null;
  let status = ""; let notes = ""; let loading = true; let busy = false; let error = ""; let saved = "";

  async function load(): Promise<void> { loading = true; error = ""; try { tx = await transactionsApi.get(id); status = tx.status; notes = tx.notes || ""; } catch (err) { error = err instanceof Error ? err.message : "Unable to load transaction."; } finally { loading = false; } }
  async function save(): Promise<void> { busy = true; saved = ""; error = ""; try { tx = await transactionsApi.update(id, { status, notes }); saved = "Transaction updated."; } catch (err) { error = err instanceof Error ? err.message : "Unable to update transaction."; } finally { busy = false; } }
  onMount(load);
</script>

{#if loading}<Loading />{:else if error && !tx}<ErrorState message={error} retry={load} />{:else if tx}
  <div class="page-heading"><div><h2>Transaction detail</h2><p class="receipt-code">{tx.receipt_code}</p></div><button class="btn" on:click={() => navigate(routePath("transactions"))}>← Back</button></div>
  {#if error}<div class="alert alert-error">{error}</div>{/if}{#if saved}<div class="alert alert-success">{saved}</div>{/if}
  <div class="grid grid-wide"><div class="stack"><section class="card card-pad"><div class="split"><div><p class="kpi-label">Receipt code</p><h3 class="receipt-code" style="font-size:20px;color:var(--accent);margin:5px 0 0">{tx.receipt_code}</h3></div><StatusBadge status={tx.status} /></div><div class="detail-grid" style="margin-top:24px"><div class="detail-item"><label>Company</label><p>{tx.company_name}</p></div><div class="detail-item"><label>Station</label><p>{tx.station_name}</p></div><div class="detail-item"><label>Church</label><p>{tx.church_name}</p></div><div class="detail-item"><label>Agent</label><p>{tx.agent_username}</p></div><div class="detail-item"><label>Fuel type</label><p>{tx.fuel_type_name}</p></div><div class="detail-item"><label>Currency</label><p>{tx.currency_used}</p></div><div class="detail-item"><label>Amount USD</label><p>{money(tx.amount_usd)}</p></div><div class="detail-item"><label>Amount CDF</label><p>{money(tx.amount_cdf, "CDF")}</p></div><div class="detail-item"><label>Exchange rate</label><p>{tx.exchange_rate}</p></div><div class="detail-item"><label>Driver phone</label><p>{tx.driver_phone || "—"}</p></div><div class="detail-item"><label>Created</label><p>{dateTime(tx.created_at)}</p></div><div class="detail-item"><label>Sync ID</label><p class="receipt-code">{tx.sync_id || "—"}</p></div></div><div class="detail-section levy-highlight"><div><span>2% charity levy</span><strong>{money(tx.levy_amount_usd)}</strong></div><div><span>CDF equivalent</span><strong>{money(tx.levy_amount_cdf, "CDF")}</strong></div></div>{#if tx.notes}<div class="detail-section"><h3>Notes</h3><p>{tx.notes}</p></div>{/if}</section><section class="card"><div class="card-header"><div><h3>Audit trail</h3><p>Recorded changes to this transaction</p></div></div>{#if tx.audit_logs?.length}<div class="audit-list">{#each tx.audit_logs as log}<div class="audit-row"><div><strong>{log.field_name}</strong><p>{log.old_value || "—"} → {log.new_value || "—"}</p></div><div class="muted text-right"><span>{log.changed_by_username || "System"}</span><small>{dateTime(log.changed_at)}</small></div></div>{/each}</div>{:else}<div class="empty-state">No changes recorded.</div>{/if}</section></div><aside>{#if can("update_transaction_status")}<section class="card card-pad"><h3 class="section-title">Update status</h3><p class="section-subtitle">Only NGO admins can update transaction status.</p><form on:submit|preventDefault={save} style="margin-top:18px"><div class="form-field"><label class="field-label" for="tx-detail-status">Status</label><select id="tx-detail-status" class="field" bind:value={status}><option value="PENDING">Pending</option><option value="VERIFIED">Verified</option><option value="REMITTED">Remitted</option></select></div><div class="form-field" style="margin-top:14px"><label class="field-label" for="tx-detail-notes">Notes</label><textarea id="tx-detail-notes" class="field" bind:value={notes} rows="4"></textarea></div><button class="btn btn-primary" style="width:100%;margin-top:14px" disabled={busy}>{busy ? "Saving…" : "Save changes"}</button></form></section>{/if}</aside></div>
{:else}<div class="empty-state">Transaction not found.</div>{/if}

<style>
  .levy-highlight{display:flex;justify-content:space-between;gap:20px;background:var(--ok-soft);border-radius:9px;padding:15px}.levy-highlight span,.levy-highlight strong{display:block}.levy-highlight span{font-size:10px;color:var(--ok);font-weight:600}.levy-highlight strong{font:600 20px "IBM Plex Mono",monospace;color:var(--money);margin-top:4px}.audit-list{padding:0 20px}.audit-row{display:flex;justify-content:space-between;gap:15px;padding:14px 0;border-bottom:1px solid var(--line);font-size:12px}.audit-row:last-child{border-bottom:0}.audit-row p{margin:5px 0 0;color:var(--muted)}.audit-row small,.audit-row span{display:block;font-size:10px;margin-top:4px}
</style>

// freddy/server/spa/src/pages/TransactionDetail.tsx
import { useState, type FormEvent } from "react";
import { Link, useParams } from "react-router-dom";
import { useTranslation } from "react-i18next";

import { useTransaction, useUpdateTransaction } from "@/api/hooks";
import { useAuth } from "@/auth/AuthProvider";
import { Card, DetailRow, ErrorState, Spinner, StatusBadge } from "@/components/ui";
import { useToast } from "@/components/Toast";
import { cdf, dateTime, number, orDash, usd } from "@/lib/format";

const STATUSES = ["PENDING", "VERIFIED", "REMITTED"];

export default function TransactionDetail() {
  const { id } = useParams<{ id: string }>();
  const { t } = useTranslation();
  const { can } = useAuth();
  const toast = useToast();

  const query = useTransaction(id);
  const update = useUpdateTransaction(id!);
  const [status, setStatus] = useState<string | null>(null);
  const [notes, setNotes] = useState<string | null>(null);

  if (query.isLoading) return <Spinner />;
  if (query.isError || !query.data) {
    return <ErrorState onRetry={() => void query.refetch()} />;
  }

  const tx = query.data;
  const editable = can("update_transaction_status");

  async function onSubmit(event: FormEvent) {
    event.preventDefault();
    try {
      await update.mutateAsync({
        status: status ?? tx.status,
        notes: notes ?? tx.notes ?? "",
      });
      toast.success(t("tx.updated", { code: tx.receipt_code }));
      setStatus(null);
      setNotes(null);
    } catch (error) {
      toast.error(error instanceof Error ? error.message : t("common.error"));
    }
  }

  return (
    <div className="space-y-4">
      <header className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <Link to="/transactions" className="text-xs text-muted hover:underline">
            ← {t("tx.title")}
          </Link>
          <h1 className="receipt-code text-lg font-semibold">{tx.receipt_code}</h1>
        </div>
        <StatusBadge status={tx.status} />
      </header>

      <div className="grid gap-4 lg:grid-cols-3">
        <Card className="lg:col-span-2" title={t("tx.detailTitle")}>
          <div className="grid gap-x-8 sm:grid-cols-2">
            <DetailRow label={t("tx.company")} value={tx.company_name} />
            <DetailRow
              label={t("tx.station")}
              value={
                <Link to={`/stations/${tx.station}`} className="hover:underline">
                  {tx.station_name}
                </Link>
              }
            />
            <DetailRow
              label={t("tx.church")}
              value={
                <Link to={`/churches/${tx.church}`} className="hover:underline">
                  {tx.church_name}
                </Link>
              }
            />
            <DetailRow
              label={t("tx.agent")}
              value={
                <Link to={`/agents/${tx.agent}`} className="hover:underline">
                  {tx.agent_username}
                </Link>
              }
            />
            <DetailRow label={t("tx.fuelType")} value={tx.fuel_type_name} />
            <DetailRow label={t("tx.currency")} value={tx.currency_used} />
            <DetailRow label={t("tx.amountUsd")} value={usd(tx.amount_usd)} />
            <DetailRow label={t("tx.amountCdf")} value={cdf(tx.amount_cdf)} />
            <DetailRow
              label={t("tx.levyUsd")}
              value={<span className="money">{usd(tx.levy_amount_usd, 4)}</span>}
            />
            <DetailRow label={t("tx.levyCdf")} value={cdf(tx.levy_amount_cdf)} />
            <DetailRow label={t("tx.exchangeRate")} value={number(tx.exchange_rate)} />
            <DetailRow label={t("tx.driverPhone")} value={orDash(tx.driver_phone)} />
            <DetailRow label={t("common.date")} value={dateTime(tx.created_at)} />
            <DetailRow label={t("common.notes")} value={orDash(tx.notes)} />
          </div>
        </Card>

        {editable && (
          <Card title={t("common.status")}>
            <form onSubmit={onSubmit} className="space-y-3">
              <div className="flex flex-col gap-1">
                <label htmlFor="status" className="text-xs font-medium">
                  {t("common.status")}
                </label>
                <select
                  id="status"
                  className="field"
                  value={status ?? tx.status}
                  onChange={(event) => setStatus(event.target.value)}
                >
                  {STATUSES.map((option) => (
                    <option key={option} value={option}>
                      {t(`status.${option}`)}
                    </option>
                  ))}
                </select>
              </div>

              <div className="flex flex-col gap-1">
                <label htmlFor="notes" className="text-xs font-medium">
                  {t("common.notes")}
                </label>
                <textarea
                  id="notes"
                  rows={3}
                  className="field field-textarea"
                  value={notes ?? tx.notes ?? ""}
                  onChange={(event) => setNotes(event.target.value)}
                />
              </div>

              <button
                type="submit"
                className="btn btn-primary w-full"
                disabled={update.isPending}
              >
                {update.isPending ? t("common.saving") : t("common.save")}
              </button>
            </form>
          </Card>
        )}
      </div>

      <Card title={t("tx.auditTrail")} bodyClassName="">
        {tx.audit_logs.length === 0 ? (
          <p className="px-4 py-8 text-center text-sm text-muted">{t("tx.noAudit")}</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="tbl tbl-zebra">
              <thead>
                <tr>
                  <th>{t("tx.field")}</th>
                  <th>{t("tx.oldValue")}</th>
                  <th>{t("tx.newValue")}</th>
                  <th>{t("tx.changedBy")}</th>
                  <th>{t("tx.changedAt")}</th>
                  <th>{t("audit.ip")}</th>
                </tr>
              </thead>
              <tbody>
                {tx.audit_logs.map((log) => (
                  <tr key={log.id}>
                    <td className="font-medium">{log.field_name}</td>
                    <td>
                      <span className="badge badge-CANCELLED">{orDash(log.old_value)}</span>
                    </td>
                    <td>
                      <span className="badge badge-VERIFIED">{orDash(log.new_value)}</span>
                    </td>
                    <td>{orDash(log.changed_by_username)}</td>
                    <td className="whitespace-nowrap text-xs text-muted">
                      {dateTime(log.changed_at)}
                    </td>
                    <td className="num text-xs text-muted">{orDash(log.ip_address)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}
